// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gupylnbccmysljxkbfhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cHlsbmJjY215c2xqeGtiZmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzYxNDIsImV4cCI6MjA2NzMxMjE0Mn0.Hl1oeeRIY9vBwzeIUiQnrBGNkYebh4h-yBWYp7-UJ8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});