// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amxfqnrvqupuciuqkkti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFteGZxbnJ2cXVwdWNpdXFra3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTA5NjgsImV4cCI6MjA2NjgyNjk2OH0.0g7dA-8_xLDitrHUFKOKVF1f4xyZ3uhP9ILq9KN69rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});